### ISSUE TITLE
Getting "FastifyError [Error]: fastify-plugin: mercurius-validation - expected '4.x' fastify version, '5.0.0' is installed" error when trying to upgrade to fastify v5.0.0

### ISSUE THREAD

**Issue by rahulpol10** [mercurius-js/validation#128]
I am trying to upgrade fastify version in my project from 4.28.1 to 5.0.0 but I am getting the mentioned error.

The latest version of mercurius-validation is 5.0.0 which supports fastify 4.28.1
Any idea when you will upgrade mercurius-validation to support fastify 5.x

**Comment by jonnydgreen** [comment]
Thanks for letting us know, this will be sorted this week :)

**Comment by rahulpol10** [comment]
Any update on this?

**Comment by jonnydgreen** [comment]
@rahulpol10 v6.0.0 should be released now with this fix - let us know if you run into any issues!
